### ISSUE TITLE
WorkJewler.cpp and FilmIdol Linker errors

### ISSUE THREAD

**Issue by Flamingboom** [crazywm/crazys-wm-mod#14]
Hello, I assume that this would be the correct place to post a report of this caliber and not the bug report thread, but please tell me if I'm wrong and I'll move the report

I downloaded a copy of the source code and began to look around it yesterday, when I first found that WorkFilmIdol.cpp was missing from the project. I assume this was intentional however, as every reference to it had been commented out in the code.

However upon removing that file from the solution explorer, I tried recompiling and found that WorkJewler.cpp was also missing with out being commented out from the code, is it not included in the repository intentionally?

**Comment by crazywm** [comment]
Its there just need to added it to the project
